name: LibraryAppCI

on: 
  push: 
    branches: 
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Create .env file
      run: |
        cat > .env <<EOF
        FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}}
        FIREBASE_APP_ID=${{secrets.FIREBASE_APP_ID}}
        FIREBASE_MESSAGING_SENDER_ID=${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
        FIREBASE_PROJECT_ID=${{secrets.FIREBASE_PROJECT_ID}}
        FIREBASE_STORAGE_BUCKET=${{secrets.FIREBASE_STORAGE_BUCKET}}
        EOF
    - name: Display .env file contents
      run: cat .env
    - name: Display Root directory
      run: ls -la
    - name: List all directories
      run: find . -type d
    - name: List all directories and files
      run: find . -print
    - uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: subosito/flutter-action@v2.14.0
      with: 
        channel: 'stable'
    - run: flutter clean
    - run: flutter pub get
    - name: build apk
      run: flutter build apk --release
    - name: upload artifact to github 
      uses: actions/upload-artifact@v4.3.5
      with:
        name: apk-release
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: upload artifact to firebase distribution 
      uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{secrets.CREDENTIAL_CONTENT}}
        file: build/app/outputs/flutter-apk/app-release.apk
        groups: tester
        debug: true
          
    
