name: LibraryAppCI

on: 
  push: 
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distributin: 'temurin'
    - uses: subosito/flutter-action@v2.14.0
      with: 
        channel: 'stable'
    - run: flutter clean
    - run: flutter pub get
    - run: flutter build apk --release
    - uses: action/upload-artifact@v4.3.1
      with:
        name: apk-release
        path: build/app/outputs/flutter-apk/app-release.apk
    
