name: LibraryAppCI

on: 
  push: 
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: subosito/flutter-action@v2.14.0
      with: 
        channel: 'stable'
    - run: flutter clean
    - run: flutter pub get
    - run: flutter build apk --release
    - uses: actions/upload-artifact@v4.3.5
      with:
        name: apk-release
        path: build/app/outputs/flutter-apk/app-release.apk
    - uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{secrets.CREDENTIAL_CONTENT}}
        file: build/app/outputs/flutter-apk/app-release.apk
        groups: tester
        debug: true
          
    
